package tfsapps.treasurehunt;

/**
 * Created by FURUKAWA on 2017/11/03.
 */

import android.content.Context;
import android.database.DatabaseUtils;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class MyOpenHelper extends SQLiteOpenHelper
{
    private static final String TABLE = "appinfo";
    public MyOpenHelper(Context context) {
        super(context, "AppDB", null, 1);
    }
    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL("create table " + TABLE + "("
                + "isopen integer,"       //DBオープン
                + "level integer,"
                + "stamina integer,"
                + "money integer,"
                + "coin integer,"
                + "gold integer,"
                + "silver integer,"
                + "bronze integer,"
                + "stage integer,"
                + "scoop integer,"
                + "goggles integer,"
                + "ore_1 integer,"
                + "ore_2 integer,"
                + "ore_3 integer,"
                + "item_1 integer,"
                + "item_2 integer,"
                + "item_3 integer,"
                + "syssw_1 integer,"
                + "syssw_2 integer,"
                + "syssw_3 integer,"
                + "syssw_4 integer,"
                + "syssw_5 integer,"
                + "story integer,"
                + "data_1 integer,"
                + "data_2 integer,"
                + "data_3 integer,"
                + "data_4 integer,"
                + "data_5 integer,"
                + "data_6 integer,"
                + "data_7 integer,"
                + "data_8 integer,"
                + "data_9 integer,"
                + "data_10 integer,"
                + "data_11 integer,"
                + "data_12 integer,"
                + "data_13 integer,"
                + "data_14 integer,"
                + "data_15 integer,"
                + "data_16 integer,"
                + "data_17 integer,"
                + "data_18 integer,"
                + "data_19 integer,"
                + "data_20 integer,"
                + "data_21 integer,"
                + "data_22 integer,"
                + "data_23 integer,"
                + "data_24 integer,"
                + "data_25 integer,"
                + "data_26 integer,"
                + "data_27 integer,"
                + "data_28 integer,"
                + "data_29 integer,"
                + "data_30 integer,"
                + "data_31 integer,"
                + "data_32 integer,"
                + "data_33 integer,"
                + "data_34 integer,"
                + "data_35 integer,"
                + "data_36 integer,"
                + "data_37 integer,"
                + "data_38 integer,"
                + "data_39 integer,"
                + "data_40 integer,"
                + "data_41 integer,"
                + "data_42 integer,"
                + "data_43 integer,"
                + "data_44 integer,"
                + "data_45 integer,"
                + "data_46 integer,"
                + "data_47 integer,"
                + "data_48 integer,"
                + "data_49 integer,"
                + "data_50 integer,"
                + "data_51 integer,"
                + "data_52 integer,"
                + "data_53 integer,"
                + "data_54 integer,"
                + "data_55 integer,"
                + "data_56 integer,"
                + "data_57 integer,"
                + "data_58 integer,"
                + "data_59 integer,"
                + "data_60 integer,"
                + "data_61 integer,"
                + "data_62 integer,"
                + "data_63 integer,"
                + "data_64 integer,"
                + "data_65 integer,"
                + "data_66 integer,"
                + "data_67 integer,"
                + "data_68 integer,"
                + "data_69 integer,"
                + "data_70 integer,"
                + "data_71 integer,"
                + "data_72 integer,"
                + "data_73 integer,"
                + "data_74 integer,"
                + "data_75 integer,"
                + "data_76 integer,"
                + "data_77 integer,"
                + "data_78 integer,"
                + "data_79 integer,"
                + "data_80 integer,"
                + "data_81 integer,"
                + "data_82 integer,"
                + "data_83 integer,"
                + "data_84 integer,"
                + "data_85 integer,"
                + "data_86 integer,"
                + "data_87 integer,"
                + "data_88 integer,"
                + "data_89 integer,"
                + "data_90 integer,"
                + "data_91 integer,"
                + "data_92 integer,"
                + "data_93 integer,"
                + "data_94 integer,"
                + "data_95 integer,"
                + "data_96 integer,"
                + "data_97 integer,"
                + "data_98 integer,"
                + "data_99 integer,"
                + "data_100 integer);");
    }
    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
    }
}
